module.exports = [
  // { name: 'vue', library: 'Vue', js: 'https://cdn.jsdelivr.net/npm/vue@2.6.11/dist/vue.min.js', css: '' },
  // { name: 'vue-i18n', library: 'VueI18n', js: 'https://cdn.jsdelivr.net/npm/vue-i18n@8.17.3/dist/vue-i18n.min.js', css: '' },
  // { name: 'vue-router', library: 'VueRouter', js: 'https://cdn.jsdelivr.net/npm/vue-router@3.1.6/dist/vue-router.min.js', css: '' },
  // { name: 'vuex', library: 'Vuex', js: 'https://cdn.jsdelivr.net/npm/vuex@3.4.0/dist/vuex.js', css: '' },
  // { name: 'axios', library: 'axios', js: 'https://cdn.jsdelivr.net/npm/axios@0.19.2/dist/axios.min.js', css: '' },
  // { name: 'element-ui', library: 'ELEMENT', js: 'https://cdn.jsdelivr.net/npm/element-ui@2.13.1/lib/index.js'/* , css: 'https://cdn.jsdelivr.net/npm/element-ui@2.13.1/lib/theme-chalk/index.css' */ },
  // { name: 'lodash', library: '_', js: 'https://cdn.jsdelivr.net/npm/lodash@4.17.15/lodash.min.js', css: '' },
  // { name: 'js-cookie', library: 'Cookies', js: 'https://cdn.jsdelivr.net/npm/js-cookie@2.2.1/src/js.cookie.min.js', css: '' },
  // { name: 'lowdb', library: 'low', js: 'https://cdn.jsdelivr.net/npm/lowdb@1.0.0/dist/low.min.js', css: '' },
  // { name: 'lowdb/adapters/LocalStorage', library: 'LocalStorage', js: 'https://cdn.jsdelivr.net/npm/lowdb@1.0.0/dist/LocalStorage.min.js', css: '' },
  // { name: '', library: '', js: 'https://at.alicdn.com/t/font_1760192_8add3xcxs4u.js', css: '' },
  // { name: '', library: '', js: '', css: 'https://cdn.jsdelivr.net/npm/font-awesome@latest/css/font-awesome.min.css' },
  // { name: '', library: '', js: '', css: 'https://cdn.jsdelivr.net/npm/font-awesome-animation@0.2.1/dist/font-awesome-animation.min.css' },

  // CN
  { name: 'vue', library: 'Vue', js: 'https://cdn.bootcdn.net/ajax/libs/vue/2.6.11/vue.min.js', css: '' },
  { name: 'vue-i18n', library: 'VueI18n', js: 'https://cdn.bootcdn.net/ajax/libs/vue-i18n/8.17.3/vue-i18n.min.js', css: '' },
  { name: 'vue-router', library: 'VueRouter', js: 'https://cdn.bootcdn.net/ajax/libs/vue-router/3.1.6/vue-router.min.js', css: '' },
  { name: 'vuex', library: 'Vuex', js: 'https://cdn.bootcdn.net/ajax/libs/vuex/3.5.1/vuex.js', css: '' }, // 找不到 3.4.0
  { name: 'axios', library: 'axios', js: 'https://cdn.bootcdn.net/ajax/libs/axios/0.19.2/axios.min.js', css: '' },
  { name: 'element-ui', library: 'ELEMENT', js: 'https://cdn.bootcdn.net/ajax/libs/element-ui/2.13.1/index.js'/* , css: 'https://cdn.jsdelivr.net/npm/element-ui@2.13.1/lib/theme-chalk/index.css' */ },
  { name: 'lodash', library: '_', js: 'https://cdn.bootcdn.net/ajax/libs/lodash.js/4.17.15/lodash.min.js', css: '' },
  { name: 'js-cookie', library: 'Cookies', js: 'https://cdn.bootcdn.net/ajax/libs/js-cookie/2.2.1/js.cookie.min.js', css: '' },
  { name: 'lowdb', library: 'low', js: 'https://cdn.bootcdn.net/ajax/libs/lowdb/1.0.0/low.min.js', css: '' },
  { name: 'lowdb/adapters/LocalStorage', library: 'LocalStorage', js: 'https://cdn.bootcdn.net/ajax/libs/lowdb/1.0.0/low.min.js', css: '' },
  { name: '', library: '', js: 'https://at.alicdn.com/t/font_1760192_8add3xcxs4u.js', css: '' },
  { name: '', library: '', js: '', css: 'https://cdn.bootcdn.net/ajax/libs/font-awesome/5.15.2/css/fontawesome.min.css' },
  { name: '', library: '', js: '', css: 'https://cdn.bootcdn.net/ajax/libs/font-awesome-animation/0.2.1/font-awesome-animation.min.css' },
]